### ISSUE TITLE
idea 视频教程？

### ISSUE THREAD

**Issue by afredlyj** [lightningMan/config#2]
我记得您有一个idea的视频教程，方便共享一下地址吗？

**Comment by lightningMan** [comment]
http://i.youku.com/i/UMTgzNTc0MzE3Ng==?spm=0.0.0.0.0kprSy

多谢支持

**Comment by afredlyj** [comment]
tks，很给力

**Comment by afredlyj** [comment]
第一篇打不开了？一直加载中

**Comment by lightningMan** [comment]
这里有高清版
http://v.qq.com/x/page/t0163iqlus1.html
http://v.qq.com/x/page/t0182czzfrv.html
