### ISSUE TITLE
关于setting2016

### ISSUE THREAD

**Issue by zzcv** [lightningMan/config#4]
LZ有留意到您最近有更新Setting 不知能否大致说下更新了一些啥细节啊~😄😄
主要我本地的KeyMap已完全照搬了您的配置，都是看了您分享的视频长草的😄😄

**Comment by lightningMan** [comment]
额，我commit里面忘了写了，已经不怎么记得了，都是新增的快捷键积累的一定程度才会放上去哈

PS：多谢支持

**Comment by zzcv** [comment]
😄😄。忍不住我就点了import setting.（当然只勾选了KeyMap 和Template）
🙏🙏
By Tory
On Wed, Jan 4, 2017 at 5:33 PM, the_flash <notifications@github.com> wrote:
额，我commit里面忘了写了，已经不怎么记得了，都是新增的快捷键积累的一定程度才会放上去哈

PS：多谢支持

**Comment by lightningMan** [comment]
我想起来了，上次应该是2016版本的IDE的keymap，如果你使用2016版本，可以使用这个jar包，keymap基本上和老的版本的jdk一样哈

**Comment by zzcv** [comment]
我发现貌似您把全局查找文件的快捷键给替换成当前文件内查找了，话说这个功能应该很常用啊。。- -😄😄

By Tory
On Wed, Jan 4, 2017 at 5:36 PM, the_flash <notifications@github.com> wrote:
我想起来了，上次应该是2016版本的IDE的keymap，如果你使用2016版本，可以使用这个jar包，keymap基本上和老的版本的jdk一样哈

**Comment by lightningMan** [comment]
有点不记得了，现在是正常的快捷键，mac：CTRL+Shift+F 全局查找字符串，CTRL+CMD+F 全屏，可以自行设置哈
