### ISSUE TITLE
关于keyMap导入

### ISSUE THREAD

**Issue by zzcv** [lightningMan/config#5]
您好，由于idea 升级至2019.2 版本后，无法继续import 2017的导出jar
不知道是我自己误操作覆盖了，还是什么原因导致我现在整个keyMap对应不上了。
不知您当前是否也有升级idea版本呢？如也同样升级至2019 or 2018版
能否麻烦您再导出一份配置jar，感激不尽。谢谢！🙏

**Comment by lightningMan** [comment]
好像现在确实是导入不了了，可以下载一个旧一些的版本，然后导入，最后通过 idea 的账号机制来同步配置
